name: Build with MSYS2 (ucrt64) and Sign

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        release: true
        update: true
        install: >-
          base-devel
          git
          make
          mingw-w64-ucrt-x86_64-gcc

    - name: Print g++ version
      shell: msys2 {0}
      run: g++ --version

    - name: Clean previous build
      shell: msys2 {0}
      run: make clean

    - name: Build project
      shell: msys2 {0}
      run: make all

    - name: Decode certificate
      run: |
        echo "${{ secrets.CERT_PFX_BASE64 }}" | base64 -d > devcert.pfx
      shell: bash

    - name: Sign executables
      run: |
        $signtool = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin\" -Recurse -Filter signtool.exe |
                    Where-Object { $_.FullName -like "*x64*" } |
                    Select-Object -First 1

        if (-not $signtool) {
          throw "signtool.exe not found."
        }

        Get-ChildItem -Path output\*.exe | ForEach-Object {
          & "$($signtool.FullName)" sign `
            /f devcert.pfx `
            /p "${{ secrets.CERT_PASSWORD }}" `
            /fd sha256 `
            /td sha256 `
            /tr http://timestamp.digicert.com `
            $_.FullName
        }
      shell: powershell


    - name: Upload signed executable
      uses: actions/upload-artifact@v4
      with:
        name: Connect4
        path: output/*.exe
