name: Build with MSYS2 (ucrt64) and Sign

on:
  workflow_dispatch:

jobs:
  build:
    name: Build with MSYS2 (UCRT64)
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          base-devel
          git
          make
          mingw-w64-ucrt-x86_64-gcc

    - name: Print g++ version
      shell: msys2 {0}
      run: g++ --version

    - name: Clean previous build
      shell: msys2 {0}
      run: make clean

    - name: Build project
      shell: msys2 {0}
      run: make all
      
    - name: Upload built EXE
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-executables
        path: output/*.exe

  sign:
    name: Sign Executables
    runs-on: windows-latest
    needs: build  # wait for build job to finish

    steps:
    - name: Download unsigned EXE
      uses: actions/download-artifact@v4
      with:
        name: unsigned-executables
        path: unsigned

    - name: Decode signing certificate
      run: |
        echo "${{ secrets.CERT_PFX_BASE64 }}" | base64 -d > devcert.pfx
      shell: bash

    - name: Sign EXE files
      run: |
        $signtool = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin\" -Recurse -Filter signtool.exe |
                      Where-Object { $_.FullName -like "*x64*" } |
                      Select-Object -First 1

        if (-not $signtool) {
          throw "signtool.exe not found."
        }

        Get-ChildItem -Path unsigned\*.exe | ForEach-Object {
          & "$($signtool.FullName)" sign `
            /f devcert.pfx `
            /p "${{ secrets.CERT_PASSWORD }}" `
            /fd sha256 `
            /td sha256 `
            /tr http://timestamp.digicert.com `
            $_.FullName
        }
      shell: powershell

    - name: Upload signed EXEs
      uses: actions/upload-artifact@v4
      with:
        name: signed-executables
        path: unsigned/*.exe
